var mc = [
 // Minecraft
 { name: "Stone Age", description: "Mine stone with your new pickaxe", color: "DarkGray"},
 { name: "Getting an Upgrade", description: "Construct a better pickaxe", color: "DarkGray" },
 { name: "Acquire Hardware", description: "Smelt an iron ingot", color: "DarkGray" },
 { name: "Suit Up", description: "Protect yourself with a piece of iron armor", color: "DarkGray" },
 { name: "Hot Stuff", description: "Fill a bucket with lava", color: "DarkGray" },
 { name: "Isn't It Iron Pick", description: "Upgrade your pickaxe", color: "DarkGray" },
 { name: "Not Today, Thank You", description: "Deflect a projectile with a shield", color: "DarkGray" },
 { name: "Ice Bucket Challenge", description: "Obtain a block of obsidian", color: "DarkGray" },
 { name: "Diamonds!", description: "Acquire diamonds", color: "DarkGray" },
 { name: "We Need to Go Deeper", description: "Build, light and enter a Nether Portal", color: "DarkGray" },
 { name: "Cover Me With Diamonds", description: "Diamond armor saves lives", color: "DarkGray" },
 { name: "Enchanter", description: "Enchant an item at an Enchanting Table", color: "DarkGray" },
 { name: "Zombie Doctor", description: "Weaken and then cure a Zombie Villager", color: "DarkGray" },
 { name: "Eye Spy", description: "Follow an Eye of Ender", color: "DarkGray" },
 { name: "The End?", description: "Enter the End Portal", color: "DarkGray" },
 // Nether
 { name: "Return to Sender", description: "Destroy a Ghast with a fireball", color: "IndianRed" },
 { name: "Those Were the Days", description: "Enter a Bastion Remnant", color: "IndianRed" },
 { name: "Hidden in the Depths", description: "Obtain Ancient Debris", color: "IndianRed" },
 { name: "Subspace Bubble", description: "Use the Nether to travel 7 km in the Overworld", color: "IndianRed" },
 { name: "A Terrible Fortress", description: "Break your way into a Nether Fortress", color: "IndianRed" },
 { name: "Who is Cutting Onions?", description: "Obtain Crying Obsidian", color: "IndianRed" },
 { name: "Oh Shiny", description: "Distract Piglins with gold", color: "IndianRed" },
 { name: "This Boat Has Legs", description: "Ride a Strider with a Warped Fungus on a Stick", color: "IndianRed" },
 { name: "Uneasy Alliance", description: "Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it", color: "IndianRed" },
 { name: "War Pigs", description: "Loot a chest in a Bastion Remnant", color: "IndianRed" },
 { name: "Country Lode, Take Me Home", description: "Use a compass on Lodestone", color: "IndianRed" },
 { name: "Cover Me in Debris", description: "Get a full suit of Netherite armor", color: "IndianRed" },
 { name: "Spooky Scary Skeleton", description: "Obtain a Wither Skeleton's skull", color: "IndianRed" },
 { name: "Into Fire", description: "Relieve a Blaze of its rod", color: "IndianRed" },
 { name: "Not Quite \"Nine\" Lives", description: "Charge a Respawn Anchor to the maximum", color: "IndianRed" },
 { name: "Hot Tourist Destinations", description: "Explore all Nether biomes", color: "IndianRed" },
 { name: "Withering Heights", description: "Summon the Wither", color: "IndianRed" }, 
 { name: "Local Brewery", description: "Brew a potion", color: "IndianRed" }, 
 { name: "Bring Home the Beacon", description: "Construct and place a beacon", color: "IndianRed" }, 
 { name: "A Furious Cocktail", description: "Have every potion effect applied at the same time", color: "IndianRed" }, 
 { name: "Beaconator", description: "Bring a beacon to full power", color: "IndianRed" }, 
 { name: "How Did We Get Here?", description: "Have every effect applied at the same time", color: "IndianRed" }, 
 // End
 { name: "Free the End", description: "Good luck", color: "DarkKhaki" }, 
 { name: "The Next Generation", description: "Hold the Dragon Egg", color: "DarkKhaki" }, 
 { name: "Remote Getaway", description: "Escape the island", color: "DarkKhaki" }, 
 { name: "The End... Again...", description: "Respawn the Ender Dragon", color: "DarkKhaki" }, 
 { name: "You Need a Mint", description: "Collect dragon's breath in a glass bottle", color: "DarkKhaki" }, 
 { name: "The City at the End of the Game", description: "Go on in, what could happen?", color: "DarkKhaki" }, 
 { name: "Sky's the Limit", description: "Find elytra", color: "DarkKhaki" }, 
 { name: "Great View From Up Here", description: "Levitate up 50 blocks from the attacks of a Shulker", color: "DarkKhaki" }, 
 // Adventure
 { name: "Voluntary Exile", description: "Kill a raid captain. Maybe consider staying away from villages for the time being...", color: "DeepSkyBlue" }, 
 { name: "Is It a Bird?", description: "Look at a parrot through a spyglass", color: "DeepSkyBlue" }, 
 { name: "Monster Hunter", description: "Kill any hostile monster", color: "DeepSkyBlue" }, 
 { name: "What a Deal!", description: "Successfully trade with a Villager", color: "DeepSkyBlue" },
 { name: "Sticky Situation", description: "Jump into a Honey Block to break your fall", color: "DeepSkyBlue" }, 
 { name: "Ol' Betsy", description: "Shoot a crossbow", color: "DeepSkyBlue" }, 
 { name: "Surge Protector", description: "Protect a villager from an undesired shock without starting a fire", color: "DeepSkyBlue" }, 
 { name: "Light as a Rabbit", description: "Walk on powder snow...without sinking in it", color: "DeepSkyBlue" }, 
 { name: "Sweet Dreams", description: "Sleep in a bed to change your respawn point", color: "DeepSkyBlue" },
 { name: "Hero of the Village", description: "Successfully defend a village from a raid", color: "DeepSkyBlue" }, 
 { name: "Is It a Balloon?", description: "Look at a ghast through a spyglass", color: "DeepSkyBlue" }, 
 { name: "A Throwaway Joke", description: "Throw a trident at something. Note: Throwing away your only weapon is not a good idea.", color: "DeepSkyBlue" }, 
 { name: "Take Aim", description: "Shoot something with an arrow", color: "DeepSkyBlue" },
 { name: "Monsters Hunted", description: "Kill one of every hostile monster", color: "DeepSkyBlue" }, 
 { name: "Postmortal", description: "Use a Totem of Undying to cheat death", color: "DeepSkyBlue" }, 
 { name: "Hired Help", description: "Summon an Iron Golem to help defend a village", color: "DeepSkyBlue" },
 { name: "Two Birds, One Arrow", description: "Kill two Phantoms with a piercing arrow", color: "DeepSkyBlue" }, 
 { name: "Who's the Pillager Now?", description: "Give a Pillager a taste of their own medicine", color: "DeepSkyBlue" }, 
 { name: "Arbalistic", description: "Kill five unique mobs with one crossbow shot", color: "DeepSkyBlue" },
 { name: "Adventuring Time", description: "Discover every biome", color: "DeepSkyBlue" }, 
 { name: "Is It a Plane?", description: "Look at the Ender Dragon through a spyglass", color: "DeepSkyBlue" }, 
 { name: "Very Very Frightening", description: "Strike a Villager with lightning", color: "DeepSkyBlue" }, 
 { name: "Sniper Duel", description: "Kill a Skeleton from at least 50 meters away", color: "DeepSkyBlue" },
 { name: "Bullseye", description: "Hit the bullseye of a Target block from at least 30 meters away", color: "DeepSkyBlue" }, 
 // Husbandry
 { name: "Bee Our Guest", description: "Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees", color: "DarkSalmon" }, 
 { name: "The Parrots and the Bats", description: "Breed two animals together", color: "DarkSalmon" },
 { name: "Whatever Floats Your Goat!", description: "Get in a Boat and float with a Goat", color: "DarkSalmon" },
 { name: "Best Friends Forever", description: "Tame an animal", color: "DarkSalmon" }, 
 { name: "Glow and Behold!", description: "Make the text of a sign glow", color: "DarkSalmon" },
 { name: "Fishy Business", description: "Catch a fish", color: "DarkSalmon" }, 
 { name: "Total Beelocation", description: "Move a Bee Nest, with 3 bees inside, using Silk Touch", color: "DarkSalmon" },
 { name: "A Seedy Place", description: "Plant a seed and watch it grow", color: "DarkSalmon" }, 
 { name: "Wax On", description: "Apply Honeycomb to a Copper block!", color: "DarkSalmon" },
 { name: "Two by Two", description: "Breed all the animals!", color: "DarkSalmon" }, 
 { name: "A Complete Catalogue", description: "Tame all cat variants!", color: "DarkSalmon" },
 { name: "Tactical Fishing", description: "Catch a fish... without a fishing rod!", color: "DarkSalmon" }, 
 { name: "A Balanced Diet", description: "Eat everything that is edible, even if it's not good for you", color: "DarkSalmon" },
 { name: "Serious Dedication", description: "Use a Netherite ingot to upgrade a hoe, and then reevaluate your life choices", color: "DarkSalmon" },
 { name: "Wax Off", description: "Scrape Wax off of a Copper block!", color: "DarkSalmon" },
 { name: "The Cutest Predator", description: "Catch an axolotl in a bucket", color: "DarkSalmon" },
 { name: "The Healing Power of Friendship!", description: "Team up with an axolotl and win a fight", color: "DarkSalmon" }
];