var mcm = [
 // Minecraft
 //{ name: "Stone Age", description: "Mine stone with your new pickaxe", color: minecraft},
 //{ name: "Getting an Upgrade", description: "Construct a better pickaxe", color: minecraft },
 //{ name: "Acquire Hardware", description: "Smelt an iron ingot", color: minecraft },
 //{ name: "Suit Up", description: "Protect yourself with a piece of iron armor", color: minecraft },
 //{ name: "Hot Stuff", description: "Fill a bucket with lava", color: minecraft },
 //{ name: "Isn't It Iron Pick", description: "Upgrade your pickaxe", color: minecraft },
 { name: "Not Today, Thank You", description: "Deflect a projectile with a shield", color: minecraft },
 { name: "Ice Bucket Challenge", description: "Obtain a block of obsidian", color: minecraft },
 { name: "Diamonds!", description: "Acquire diamonds", color: minecraft },
 //{ name: "We Need to Go Deeper", description: "Build, light and enter a Nether Portal", color: minecraft },
 { name: "Cover Me with Diamonds", description: "Diamond armor saves lives", color: minecraft },
 { name: "Enchanter", description: "Enchant an item at an Enchanting Table", color: minecraft },
 { name: "Zombie Doctor", description: "Weaken and then cure a Zombie Villager", color: minecraft },
 { name: "Eye Spy", description: "Follow an Eye of Ender", color: minecraft },
 { name: "The End?", description: "Enter the End Portal", color: minecraft },
 // Nether
 { name: "Return to Sender", description: "Destroy a Ghast with a fireball", color: nether },
 { name: "Those Were the Days", description: "Enter a Bastion Remnant", color: nether },
 { name: "Hidden in the Depths", description: "Obtain Ancient Debris", color: nether },
 { name: "Subspace Bubble", description: "Use the Nether to travel 7 km in the Overworld", color: nether },
 { name: "A Terrible Fortress", description: "Break your way into a Nether Fortress", color: nether },
 { name: "Who is Cutting Onions?", description: "Obtain Crying Obsidian", color: nether },
 { name: "Oh Shiny", description: "Distract Piglins with gold", color: nether },
 { name: "This Boat Has Legs", description: "Ride a Strider with a Warped Fungus on a Stick", color: nether },
 //{ name: "Uneasy Alliance", description: "Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it", color: nether },
 { name: "War Pigs", description: "Loot a chest in a Bastion Remnant", color: nether },
 { name: "Country Lode, Take Me Home", description: "Use a compass on Lodestone", color: nether },
 //{ name: "Cover Me in Debris", description: "Get a full suit of Netherite armor", color: nether },
 { name: "Spooky Scary Skeleton", description: "Obtain a Wither Skeleton's skull", color: nether },
 { name: "Into Fire", description: "Relieve a Blaze of its rod", color: nether },
 { name: "Not Quite \"Nine\" Lives", description: "Charge a Respawn Anchor to the maximum", color: nether },
 // { name: "Feels like home", description: "Take a Strider for a loooong ride on a lava lake in the Overworld", color: nether },
 { name: "Hot Tourist Destinations", description: "Explore all Nether biomes", color: nether },
 //{ name: "Withering Heights", description: "Summon the Wither", color: nether }, 
 { name: "Local Brewery", description: "Brew a potion", color: nether }, 
 //{ name: "Bring Home the Beacon", description: "Construct and place a beacon", color: nether }, 
 //{ name: "A Furious Cocktail", description: "Have every potion effect applied at the same time", color: nether }, 
 //{ name: "Beaconator", description: "Bring a beacon to full power", color: nether }, 
 //{ name: "How Did We Get Here?", description: "Have every effect applied at the same time", color: nether }, 
 // End
 { name: "Free the End", description: "Good luck", color: end }, 
 { name: "The Next Generation", description: "Hold the Dragon Egg", color: end }, 
 { name: "Remote Getaway", description: "Escape the island", color: end }, 
 //{ name: "The End... Again...", description: "Respawn the Ender Dragon", color: end }, 
 { name: "You Need a Mint", description: "Collect dragon's breath in a glass bottle", color: end }, 
 { name: "The City at the End of the Game", description: "Go on in, what could happen?", color: end }, 
 //{ name: "Sky's the Limit", description: "Find elytra", color: end }, 
 { name: "Great View From Up Here", description: "Levitate up 50 blocks from the attacks of a Shulker", color: end }, 
 // Adventure
 { name: "Voluntary Exile", description: "Kill a raid captain. Maybe consider staying away from villages for the time being...", color: adventure }, 
 { name: "Is It a Bird?", description: "Look at a parrot through a spyglass", color: adventure }, 
 //{ name: "Monster Hunter", description: "Kill any hostile monster", color: adventure }, 
 //{ name: "What a Deal!", description: "Successfully trade with a Villager", color: adventure },
 { name: "Sticky Situation", description: "Jump into a Honey Block to break your fall", color: adventure }, 
 //{ name: "Ol' Betsy", description: "Shoot a crossbow", color: adventure }, 
 //{ name: "Surge Protector", description: "Protect a villager from an undesired shock without starting a fire", color: adventure }, 
 { name: "Caves & Cliffs", description: "Free fall from the top of the world (build limit) to the bottom of the world and survive", color: adventure }, 
 //{ name: "Sweet Dreams", description: "Sleep in a bed to change your respawn point", color: adventure },
 { name: "Hero of the Village", description: "Successfully defend a village from a raid", color: adventure }, 
 { name: "Is It a Balloon?", description: "Look at a ghast through a spyglass", color: adventure }, 
 { name: "A Throwaway Joke", description: "Throw a trident at something. Note: Throwing away your only weapon is not a good idea.", color: adventure }, 
 //{ name: "Take Aim", description: "Shoot something with an arrow", color: adventure },
 //{ name: "Monsters Hunted", description: "Kill one of every hostile monster", color: adventure }, 
 { name: "Postmortal", description: "Use a Totem of Undying to cheat death", color: adventure }, 
 { name: "Hired Help", description: "Summon an Iron Golem to help defend a village", color: adventure },
 { name: "Star Trader", description: "Trade with a villager at the build height limit", color: adventure },
 { name: "Two Birds, One Arrow", description: "Kill two Phantoms with a piercing arrow", color: adventure }, 
 { name: "Who's the Pillager Now?", description: "Give a Pillager a taste of their own medicine", color: adventure }, 
 //{ name: "Arbalistic", description: "Kill five unique mobs with one crossbow shot", color: adventure },
 //{ name: "Adventuring Time", description: "Discover every biome", color: adventure }, 
 { name: "Sound of Music", description: "Make the Meadows come alive with the sound of music from a jukebox", color: adventure }, 
 { name: "Light as a Rabbit", description: "Walk on powder snow...without sinking in it", color: adventure }, 
 { name: "Is It a Plane?", description: "Look at the Ender Dragon through a spyglass", color: adventure }, 
 //{ name: "Very Very Frightening", description: "Strike a Villager with lightning", color: adventure }, 
 { name: "Sniper Duel", description: "Kill a Skeleton from at least 50 meters away", color: adventure },
 { name: "Bullseye", description: "Hit the bullseye of a Target block from at least 30 meters away", color: adventure }, 
 // Husbandry
 { name: "Bee Our Guest", description: "Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees", color: husbandry }, 
 { name: "The Parrots and the Bats", description: "Breed two animals together", color: husbandry },
 { name: "Whatever Floats Your Goat!", description: "Get in a Boat and float with a Goat", color: husbandry },
 { name: "Best Friends Forever", description: "Tame an animal", color: husbandry }, 
 { name: "Glow and Behold!", description: "Make the text of a sign glow", color: husbandry },
 //{ name: "Fishy Business", description: "Catch a fish", color: husbandry }, 
 { name: "Total Beelocation", description: "Move a Bee Nest, with 3 bees inside, using Silk Touch", color: husbandry },
 //{ name: "A Seedy Place", description: "Plant a seed and watch it grow", color: husbandry }, 
 { name: "Wax On", description: "Apply Honeycomb to a Copper block!", color: husbandry },
 //{ name: "Two by Two", description: "Breed all the animals!", color: husbandry }, 
 //{ name: "A Complete Catalogue", description: "Tame all cat variants!", color: husbandry },
 { name: "Tactical Fishing", description: "Catch a fish... without a fishing rod!", color: husbandry }, 
 //{ name: "A Balanced Diet", description: "Eat everything that is edible, even if it's not good for you", color: husbandry },
 { name: "Serious Dedication", description: "Use a Netherite ingot to upgrade a hoe, and then reevaluate your life choices", color: husbandry },
 { name: "Wax Off", description: "Scrape Wax off of a Copper block!", color: husbandry },
 { name: "The Cutest Predator", description: "Catch an axolotl in a bucket", color: husbandry },
 { name: "The Healing Power of Friendship!", description: "Team up with an axolotl and win a fight", color: husbandry }
];