const all = [
	{ name: "Defeat a Boss", description: "You are Nothing", color: ashlands },
	{ name: "Obtain cross-over Content", description: "Taiyoh!", color: mistlands },
	{ name: "Play a Video Game in the Video Game", description: "Gameception", color: mistlands },
	{ name: "Slay a Slime", description: "Slippery Shinobi", color: ashlands },
	{ name: "Glitch out of Bounds", description: "", color: mistlands },
	{ name: "Get to exactly 1 HP and Survive", description: "Not even Close", color: meadows },
	{ name: "Reach a Save Point", description: "", color: black },
	{ name: "Rest by a fire", description: "8 Minutes", color: meadows },
	{ name: "Become Poisoned", description: "Weedle used Poison Sting", color: black },
	{ name: "Find an Easter Egg", description: "", color: mistlands },
	{ name: "Trigger a Gltich", description: "Cheater!", color: mistlands },
	{ name: "Open a Locked Chest", description: "Big Booty", color: meadows },
	{ name: "Die to a Naturally Occuring Trap", description: "Dead Men Tell No Tales", color: black },
	{ name: "Slay an Enemy with Another Enemy", description: "", color: ashlands },
	{ name: "Watch a Cutscene", description: "Don't Skip it!", color: meadows },
	{ name: "Slay a Zombie", description: "", color: ashlands },
	{ name: "Hurt Yourself with your own Attack", description: "Breakthrough", color: black },
	{ name: "Go through a portal", description: "We Need to Go Deeper", color: black },
	{ name: "Trigger the Credits", description: "The End", color: meadows },
	{ name: "Slay a Dragon", description: "Good Luck", color: ashlands },
	{ name: "Go to Space", description: "", color: black },
	{ name: "Fill your Inventory", description: "Encumbered?", color: meadows },
	{ name: "Automate something Indefinitely", description: "", color: plains },
	{ name: "Grow or Shrink.", description: "enghin enghin enghin", color: black },
	{ name: "Get to 0 Money", description: "", color: meadows },
	{ name: "Get to Max Money", description: "", color: meadows },
	{ name: "Defeat a Boss Without Being Hit", description: "Perfection", color: ashlands },
	{ name: "Use an Item Until it Reaches 0 Durability", description: "Doesn't need to break", color: plains },
	{ name: "Fish up not a Fish", description: "", color: plains },
	{ name: "See your Character's Reflection", description: "Mirrors Mirrors", color: black },
	{ name: "Cut Down a Tree", description: "Timber!!", color: meadows },
	{ name: "Crash the Game", description: "ƒNƒ‰ƒVƒbƒNƒRƒ\"ƒgƒ [ƒ‰,ª·K—v,Å,· B", color: mistlands },
	{ name: "Complete the Tutorial", description: "", color: meadows },
	{ name: "Get a Headshot", description: "", color: ashlands },
	{ name: "Play an Instrument", description: "Spicy Licks", color: meadows },
	{ name: "Open a Locked Door", description: "Small Key Anyone?", color: meadows },
	{ name: "Increase your Max Health", description: "Heart Breaker", color: meadows },
	{ name: "Buy Everything in a Shop", description: "Umbrella", color: plains },
	{ name: "Catch a Fish", description: "Fishy Business", color: plains },
	{ name: "Jump out of a Moving Vehicle", description: "Tuck n Roll", color: black },
	{ name: "Find a number higher than 9000", description: "Don't just write it in Chat!", color: black },
	{ name: "Take Public Transportation", description: "When's the next Train?", color: plains },
	{ name: "Go to Sleep", description: "Sweet Dreams", color: meadows },
	{ name: "Win an online Match", description: "1v1 me bro", color: ashlands },
	{ name: "Pet an Animal", description: "Feeling Petty", color: plains },
	{ name: "Take Fall Damage, and Live", description: "Lucky Break", color: meadows },
	{ name: "Achieve an 'A' Rank", description: "Not a 'S' Rank", color: black },
	{ name: "Title Drop", description: "Not a Title Sequence", color: meadows },
	{ name: "Capture a Critter", description: "I Choose You!", color: meadows },
	{ name: "Obtain a Sword", description: "It's Dangerous to go Alone", color: meadows },
	{ name: "Get an Achievement", description: "", color: meadows },
	{ name: "Plant then Harvest a Crop", description: "", color: plains }
];
