const allColor = "#A2E8CE";
const all = [
	{ name: "Defeat a Boss", description: "You are Nothing", color: allColor },
	{ name: "Obtain cross-over Content", description: "Taiyoh!", color: allColor },
	{ name: "Play a Video Game in the Video Game", description: "Gameception", color: allColor },
	{ name: "Slay a Slime", description: "Slippery Shinobi", color: allColor },
	{ name: "Glitch out of Bounds", description: "", color: allColor },
	{ name: "Get to exactly 1 HP and Survive", description: "Not even Close", color: allColor },
	{ name: "Reach a Save Point", description: "", color: allColor },
	{ name: "Rest by a fire", description: "8 Minutes", color: allColor },
	{ name: "Become Poisoned", description: "Weedle used Poison Sting", color: allColor },
	{ name: "Find an Easter Egg", description: "", color: allColor },
	{ name: "Trigger a Glitch", description: "Cheater!", color: allColor },
	{ name: "Open a Locked Chest", description: "Big Booty", color: allColor },
	{ name: "Die to a Naturally Occuring Trap", description: "Dead Men Tell No Tales", color: allColor },
	{ name: "Slay an Enemy with Another Enemy", description: "", color: allColor },
	{ name: "Watch a Cutscene", description: "Don't Skip it!", color: allColor },
	{ name: "Slay a Zombie", description: "", color: allColor },
	{ name: "Hurt Yourself with your own Attack", description: "Breakthrough", color: allColor },
	{ name: "Go through a portal", description: "We Need to Go Deeper", color: allColor },
	{ name: "Trigger the Credits", description: "The End", color: allColor },
	{ name: "Slay a Dragon", description: "Good Luck", color: allColor },
	{ name: "Go to Space", description: "", color: allColor },
	{ name: "Fill your Inventory", description: "Encumbered?", color: allColor },
	{ name: "Automate something Indefinitely", description: "", color: allColor },
	{ name: "Grow or Shrink.", description: "enghin enghin enghin", color: allColor },
	{ name: "Get to 0 Money", description: "", color: allColor },
	{ name: "Get to Max Money", description: "", color: allColor },
	{ name: "Defeat a Boss Without Being Hit", description: "Perfection", color: allColor },
	{ name: "Use an Item Until it Reaches 0 Durability", description: "Doesn't need to break", color: allColor },
	{ name: "Fish up not a Fish", description: "", color: allColor },
	{ name: "See your Character's Reflection", description: "Mirror Mirror", color: allColor },
	{ name: "Cut Down a Tree", description: "Timber!!", color: allColor },
	{ name: "Crash the Game", description: "ƒNƒ‰ƒVƒbƒNƒRƒ\"ƒgƒ [ƒ‰,ª·K—v,Å,· B", color: allColor },
	{ name: "Complete the Tutorial", description: "", color: allColor },
	{ name: "Get a Headshot", description: "", color: allColor },
	{ name: "Play an Instrument", description: "Spicy Licks", color: allColor },
	{ name: "Open a Locked Door", description: "Small Key Anyone?", color: allColor },
	{ name: "Increase your Max Health", description: "Heart Breaker", color: allColor },
	{ name: "Buy out a Shop", description: "Parasol", color: allColor },
	{ name: "Catch a Fish", description: "Fishy Business", color: allColor },
	{ name: "Jump out of a Moving Vehicle", description: "Tuck n Roll", color: allColor },
	{ name: "Find a number higher than 9000", description: "Don't just write it in Chat!", color: allColor },
	{ name: "Pay For then Take Public Transportation", description: "When's the next Train?", color: allColor },
	{ name: "Go to Sleep", description: "Sweet Dreams", color: allColor },
	{ name: "Win an online Match", description: "1v1 me bro", color: allColor },
	{ name: "Pet an Animal", description: "Feeling Petty", color: allColor },
	{ name: "Take Fall Damage, and Live", description: "Lucky Break", color: allColor },
	{ name: "Achieve an 'A' Rank", description: "Not a 'S' Rank", color: allColor },
	{ name: "Title Drop", description: "Not a Title Sequence", color: allColor },
	{ name: "Capture a Critter", description: "I Choose You!", color: allColor },
	{ name: "Obtain a Sword", description: "It's Dangerous to go Alone", color: allColor },
	{ name: "Plant then Harvest a Crop", description: "", color: allColor },
	{ name: "Win a Race", description: "", color: allColor },
	{ name: "Commit a Crime", description: "", color: allColor },
	{ name: "Draw a Dick", description: "Real Mature", color: allColor },
	{ name: "Lie", description: "How Deceptive", color: allColor },
	{ name: "Obtain a Randomized Item", description: "Without playing a Randomizer", color: allColor },
	{ name: "Find the number 69", description: "Nice", color: allColor },
	{ name: "Find the number 67", description: "six-seven", color: allColor },
	{ name: "Reach Max Level", description: "Not having levels doesn't count", color: allColor },
	{ name: "Get a NEW Steam Achievement", description: "Without reseting your achievements", color: allColor },
	{ name: "Play coop with Someone not participating in Bingo", description: "", color: allColor },
	{ name: "Win a Gold Trophy", description: "", color: allColor },
	{ name: "Bust a Ghost", description: "GhostBusters", color: allColor },
	{ name: "Complete the Dailies", description: "", color: allColor },
	{ name: "Go outside IRL", description: "Touch Grass", color: allColor },
	{ name: "Fall for 15 seconds", description: "How long?", color: allColor },
	{ name: "Transform", description: "Next time on... ", color: allColor },
	{ name: "Achieve a 30 hit combo!", description: "one two three... etc", color: allColor }
];
