const vhtm = [
 // Valheim
 // Meadows
 { name: "Boar", description: "This boar head would make for a nice decoration in any house.", color: meadows },
 { name: "Deer", description: "A fine specimen but you'll need to kill more than deer to enter Valhalla.", color: meadows },
 { name: "Neck", description: "The beady eyes and razorsharp teeth belies the ostensibly calm nature of this small lizard.", color: meadows },
 { name: "Eikthyr", description: "This severed head oozes power. Offer it to the Sacrificial Stones.", color: meadows },
 // Black Forest
 { name: "Greydwarf", description: "The mossy, severed head of a Greydwarf.", color: black },
 { name: "Greydwarf Brute", description: "It took seven blows to hack this gnarled head from its body.", color: black },
 { name: "Greydwarf Shaman", description: "It may try to come back so be sure to prune any new shoots...", color: black },
 { name: "Troll", description: "The leathery skin bears the faded tracery of ancient symbols.", color: black },
 { name: "Skeleton", description: "The expressionless grin of this skull reminds you of the inevitability of death.", color: black },
 { name: "Rancid Remains", description: "A rank and rotten skull. You're not sure why you kept it...", color: black },
 { name: "The Elder", description: "This severed head oozes power. Offer it to the Sacrificial Stones.", color: black },
 // { name: "Brenna", description: "Still burning, somehow.", color: black },
 { name: "Bear", description: "That stare is still frightening...", color: black },
 { name: "Ghost", description: "Does it still whisper about unfinished business?", color: black },
 // Swamp
 { name: "Leech", description: "Although slimy, the skin is beautifully patterned in red and black.", color: swamp },
 { name: "Draugr", description: "Bind up the mouth if it starts to whisper in the night...", color: swamp },
 { name: "Draugr Elite", description: "The dead stare of the glowing red eyes sends a shiver through your bones.", color: swamp },
 { name: "Wraith", description: "The shed skin of a wraith, a flowing robe only visible by moonlight.", color: swamp },
 { name: "Abomination", description: "It's been dead so long that it started living again.", color: swamp },
 { name: "Blob", description: "A smelly lump of sticky matter.", color: swamp },
 { name: "Bonemass", description: "Bones and viscous goo, held together by some unseen force. Offer it to the Sacrificial Stones.", color: swamp },
 { name: "Surtling", description: "Wreathed in pale flame, it still smolders like an ember.", color: swamp },
 { name: "Kvastur", description: "A witch's best friend.", color: swamp },
 // Mountain
 { name: "Wolf", description: "Frozen in death, the hair matted with blood and a silent howl lodged in its throat.", color: mountain },
 { name: "Fenring", description: "Half-way between wolf and man, its face frozen in a snarl of pain.", color: mountain },
 { name: "Stone Golem", description: "This crystalline rock formation would make for an impressive floor decoration.", color: mountain },
 { name: "Drake", description: "Still cold to the touch.", color: mountain },
 { name: "Ulv", description: "A rugged tail from a not so good boy", color: mountain },
 { name: "Cultist", description: "The fire in its eyes has still not burned out.", color: mountain },
 { name: "Moder", description: "The head of a dragon, majestic even in the rigor of death. Offer it to the Sacrificial Stones.", color: mountain },
 // { name: "Geirrhafa", description: "He's giving you an icy stare.", color: mountain },
 // Plains
 { name: "Fuling", description: "Loose folds of greenish skin gathered in around a pair of dark and hateful eyes.", color: plains },
 { name: "Fuling Berserker", description: "The huge grizzled head is as heavy as a boulder.", color: plains },
 { name: "Fuling Shaman", description: "Even killing it couldn't wipe the knowing smile from its crooked lips...", color: plains },
 { name: "Lox", description: "A giant beast's head, thatched with thick fur.", color: plains },
 { name: "Deathsquito", description: "You don't like touching this thing even when it's dead.", color: plains },
 { name: "Growth", description: "A black and sticky mess.", color: plains },
 { name: "Yagluth", description: "The crownless head of a dead king. Offer it to the Sacrificial Stones.", color: plains },
 // { name: "Zil", description: "In the choice of 'ride or die', he picked the latter.", color: plains },
 // { name: "Thungr", description: "Not so tough now.", color: plains },
 { name: "Vile", description: "These eyes are finally vacant for good.", color: plains },
 // Mistlands
 // { name: "Hare", description: "These are said to bring luck. But not for their original owner.", color: mistlands },
 // { name: "Gjall", description: "Hopefully it won't float away.", color: mistlands },
 // { name: "Tick", description: "It's a conversation piece...", color: mistlands },
 // { name: "Seeker", description: "Less delicate as they look. The leather of the wings catches the firelight as if remembering flight.", color: mistlands },
 // { name: "Seeker Soldier", description: "The head of a fallen champion.", color: mistlands },
 // { name: "Dvergr", description: "It's frankly a little troubling that you would consider hanging these on your wall...", color: mistlands },
 // { name: "The Queen", description: "She has seen enough. Offer it to the Sacrificial Stones.", color: mistlands },
 // Ocean
 { name: "Serpent", description: "The scales have dulled but the eyes are still bright.", color: ocean },
 // Ashlands
 // { name: "Asksvin", description: "Don't let yourself be fooled by the friendly smile, for it could easily bite your arm off.", color: ashlands },
 // { name: "Bonemaw", description: "A skull made up of dense bone, as dangerous as it is protective.", color: ashlands },
 // { name: "Marksman", description: "These legs could hold infinite power.", color: ashlands },
 // { name: "Warlock", description: "A warm glow seems to almost emanate from within. Handle with care.", color: ashlands },
 // { name: "Warrior", description: "Fractures line this skull, as if it has taken many hits over the years.", color: ashlands },
 // { name: "Fader", description: "The green dragon, corrupted beyond redemption. Offer him to the sacrificial stones.", color: ashlands },
 // { name: "Fallen Valkyrie", description: "Though she is dead, she yearns for the blood to flow.", color: ashlands },
 // { name: "Morgen", description: "The waking nightmare has met its end.", color: ashlands },
 // { name: "Volture", description: "It's like a vulture, but it thrives in volcanic climates.", color: ashlands }
];